### ISSUE TITLE
Syncfusion Package License

### ISSUE THREAD

**Issue by AbelTarazona** [abdulalikhan/comet_internet_speed_test#1]
Hi. I think you should update the readme because is not longer necessary to have an account key to use the Gauge's Syncfusion 😁

**Comment by abdulalikhan** [comment]
Hello! The [https://pub.dev/packages/syncfusion_flutter_gauges#installation](syncfusion_flutter_gauges Documentation) still includes a disclaimer that specifies the need for a commercial/free syncfusion community license to use the package. I can't seem to find any such information on the changelog either.

**Comment by abdulalikhan** [comment]
> Hi. I think you should update the readme because is not longer necessary to have an account key to use the Gauge's Syncfusion 😁

Hello! The [syncfusion_flutter_gauges documentation](https://pub.dev/packages/syncfusion_flutter_gauges#overview) still includes a disclaimer that specifies the need for a commercial/free syncfusion community license to use the package. I can't seem to find any such information on the changelog either.
